### ISSUE TITLE
Banned 

### ISSUE THREAD

**Issue by Adharsh26** [Mid0aria/owofarmbot#114]
The bot doesnt stop after the captcha has been detected.

![image](https://github.com/Mid0aria/owofarmbot/assets/94824979/fdba5d43-7766-43ca-ae92-4a223594d685)
![image](https://github.com/Mid0aria/owofarmbot/assets/94824979/f38e9870-0fe9-481f-9691-149dd1ca9458)

**Comment by Mid0aria** [comment]
If owo is running slowly or your internet is slow, the farm bot will not work synchronised and as a result, timings and special functions will not be able to fulfil their tasks, so situations such as bans will occur.
Long story short, the problem is with you, not the farm bot.

you can extend the times as a temporary solution
