### ISSUE TITLE
Extra Token Ban Bypass

### ISSUE THREAD

**Issue by sneazy-ibo** [Mid0aria/owofarmbot#97]
The captcha detection on my alt account doesn't get triggered if my main acc has no captcha, this will result in a ban whilst the main still hasn't been detected yet it thinks that there are no captchas.
<img width="1065" alt="image" src="https://github.com/Mid0aria/owofarmbot/assets/41344259/881e26a7-00ca-4079-a6e7-0eec9b7f0c16">

**Comment by mallusrgreatv2** [comment]
[bot.js line 1611](https://github.com/Mid0aria/owofarmbot/blob/main/bot.js#L1611) and [bot.js line 1555](https://github.com/Mid0aria/owofarmbot/blob/main/bot.js#L1555) both think that the "A" should always be capital, while the picture you sent shows the lowercase letter a. This is probably due to the bad checking.

**Comment by Mid0aria** [comment]
Oh yeah, my bad, DM has A but normal chat has a.

**Comment by mallusrgreatv2** [comment]
> Oh yeah, my bad, DM has A but normal chat has a.

@Mid0aria it should be an easy fix
`cont.toLowerCase().includes("are you a real human?")`

**Comment by Mid0aria** [comment]
> > Oh yeah, my bad, DM has A but normal chat has a.
> 
> @Mid0aria it should be an easy fix `cont.toLowerCase().includes("are you a real human?")`

Can you fix the problem and send a pr? I'm not at home
